fakenewsgui/fakenewsgui/urls.py
# pyright: reportMissingImports=false, reportUnusedVariable=warning, reportUntypedBaseClass=error
"""fakenewsgui URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include
from myapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('myapp.urls'))
   
]

fakenewsgui/myapp/urls.py
# coding: utf-8
# -*- coding: utf-8 -*-
# pyright: reportMissingImports=false, reportUnusedVariable=false, reportUntypedBaseClass=error,reportUndefinedVariable=false
import os, sys, re, time
#STEP 1-ALLOW DJANGO TO RUN FROM COMMAND LINE AND NOT BROWSER
project_path="/home/lewis/Documents/FakeNewsProject/fakenewsgui"
os.environ.setdefault("DJANGO_SETTINGS_MODULE",
"fakenewsgui.settings"),
sys.path.append(project_path)
os.chdir(project_path)

from django.core.wsgi import get_wsgi_application
application=get_wsgi_application()
from django.contrib.gis.views import feed
from django.urls import path, re_path,include
from myapp.scrapper import *
from myapp.util import *
from myapp.forms import *
from myapp.views import *
from . import *
from myapp import views

app_name='myapp'

urlpatterns = [
    path('', views.index, name='index'),
    #path('', include('base.urls')),
    #path(r'^$', 'base', name='base'),
    #path('/home/lewis/Documents/FakeNewsProject/fakenewsgui/myapp', myapp.urls),
    #path('urlForm',urlForm)
]

fakenewsgui/myapp/models.py
from django.apps import AppConfig
from django.db import models

# pyright: reportMissingImports=false, reportUnusedVariable=false, reportUntypedBaseClass=error,reportUndefinedVariable=false
#from django.db import models


class ArticleExample(models.Model):
    # This will hold the visible text for this example
    body_text = models.TextField()
    # This bias score is a left-right bias provided by Media Bias Chart, but not used in this project.
    bias_score = models.FloatField()
    bias_class = models.IntegerField()
    # quality_score comes from the Media Bias Chart data
    quality_score = models.FloatField()
    # quality_class is based on the bias score and allows us to then integrate politifact data in their
    # 4-class way, True = 4, Mostly True = 3, Mostly Fake = 2, Fake = 1
    quality_class = models.IntegerField()
    
    origin_url = models.TextField()
    origin_source = models.TextField()

class DictEntry(models.Model):
    canonWord = models.TextField()
    
class UserEntry(models.Model):
    entryURL = models.URLField(verbose_name='URL of news article')

fakenewsgui/myapp/forms.py
# this file isn't needed, I had to create it to get the crispy_tags form, then I modified that to use 
# a GET request to make the final URL shareable
# pyright: reportMissingImports=false, reportUnusedVariable=false, reportUntypedBaseClass=error,reportUndefinedVariable=false
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit, Field, Fieldset

from django.forms import ModelForm, Textarea
import pickle
import os, sys, re, time
import numpy as np
#STEP 1-ALLOW DJANGO TO RUN FROM COMMAND LINE AND NOT BROWSER
project_path="/home/lewis/Documents/FakeNewsProject/fakenewsgui"
os.environ.setdefault("DJANGO_SETTINGS_MODULE",
"fakenewsgui.settings"),
sys.path.append(project_path)
os.chdir(project_path)

from django.core.wsgi import get_wsgi_application
application=get_wsgi_application()
from django.contrib.gis.views import feed
from myapp.scrapper import *
from myapp.util import *
from myapp.models import *
from . import *


class ArticleTesterForm(ModelForm):
    def __init__(self, *args, **kwargs):
        
        # first call parent's constructor
        super(ArticleTesterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            ButtonHolder(
                Field('entryURL'),
                Submit('submit', 'Analyze', css_class='btn btn-primary')
            )
            )
     
    class Meta:
        model = UserEntry
        exclude = []

fakenewsgui/myapp/views.py
# pyright: reportMissingImports=false, reportUnusedVariable=false, reportUntypedBaseClass=error,reportUndefinedVariable=false
from django.shortcuts import render
import pandas as pd
import numpy as np
import pickle,os,sys,re,time
import pandas as pd
import numpy as np
from sklearn.metrics import *
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
#from sklearn.neural_network.multilayer_perceptron import MLPClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression



#STEP 1-ALLOW DJANGO TO RUN FROM COMMAND LINE AND NOT BROWSER
project_path="/home/lewis/Documents/FakeNewsProject/fakenewsgui"
os.environ.setdefault("DJANGO_SETTINGS_MODULE",
"fakenewsgui.settings"),
sys.path.append(project_path)
os.chdir(project_path)

from django.core.wsgi import get_wsgi_application
application=get_wsgi_application()
from django.contrib.gis.views import feed
from myapp.scrapper import *
from myapp.util import *
from myapp.forms import *
from myapp.models import *
from . import *
from django.http import Http404

# Create your views here.
def index(request):
    url = request.GET.get('u')
    if((url is not None) and (len(url) > 5)):

        # 1. Load the models from saved location
        print("STARTING")
    
        log_model = pickle.load(open('/home/lewis/Documents/FakeNewsProject/fakenewsgui/myapp/log_model.sav', 'rb'))
        svc_model = pickle.load(open('/home/lewis/Documents/FakeNewsProject/fakenewsgui/myapp/svc_model.sav', 'rb'))
        mlp_model = pickle.load(open('/home/lewis/Documents/FakeNewsProject/fakenewsgui/myapp/MLPC_model.sav', 'rb'))
        gnb_model = pickle.load(open('/home/lewis/Documents/FakeNewsProject/fakenewsgui/myapp/gaussian_model.sav', 'rb'))
        mnb_model=  pickle.load(open('/home/lewis/Documents/FakeNewsProject/fakenewsgui/myapp/multinomial_model.sav','rb'))
        bernoulli_model = pickle.load(open('/home/lewis/Documents/FakeNewsProject/fakenewsgui/myapp/bernoulli_model.sav', 'rb'))
        
        print("Models have been loaded successful.")


        cDict = loadCanonDict()
        soup = SoupStrainer()
        soup.init()
        print("Setup complete")
        print("Analyzing your link: " + url)

        if(soup.loadAddress(url)):
            
            siteArticle = buildExampleRow(soup.extractText, cDict)
        else:
            raise Http404("YOU ENTERED A URL HAVING WRONG FORMAT OR YOU ARE OFFLINE.PLEASE TRY AGAIN")
            #return render(request, '404.html', {'URL', url})

        siteArticle = siteArticle.reshape(1, -1)

        
        # 5. Send the X row to the model to produce a prediction
        svc_prediction = svc_model.predict(siteArticle)
        svc_prob = svc_model.predict_proba(siteArticle)
        

        mlp_prediction = mlp_model.predict(siteArticle)
        mlp_prob = mlp_model.predict_proba(siteArticle)
        

        log_prediction = log_model.predict(siteArticle)
        log_prob = log_model.predict_proba(siteArticle)


        gnb_prediction = gnb_model.predict(siteArticle)
        gnb_prob = gnb_model.predict_proba(siteArticle)

        mnb_prediction = mnb_model.predict(siteArticle)
        mnb_probabilities = mnb_model.predict_proba(siteArticle)

        bernoulli_prediction = bernoulli_model.predict(siteArticle)
        bernoulli_probabilities = bernoulli_model.predict_proba(siteArticle)

        countlog=0
        countsvc=0
        countbern=0
        countmlp=0
        countmnb=0
        countgnb=0

        if( log_prediction==[4] or log_prediction == [2]):
            countlog+=1
            print(countlog)

        if( svc_prediction==[4] or svc_prediction == [2]):
            countsvc+=1
            print(countsvc)

        if( mlp_prediction==[4] or mlp_prediction == [2]):
            countmlp+=1
            print(countmlp)

        if( bernoulli_prediction==[4] or bernoulli_prediction == [2]):
            countbern+=1
            print(countbern)


        if( mnb_prediction==[4] or mnb_prediction == [2]):
            countmnb+=1
            print(countmnb)

        if( gnb_prediction==[4] or gnb_prediction == [2]):
            countgnb+=1
            print(countgnb)


        counttot=countlog+countmlp+countsvc+countgnb+countmnb+countbern
        
        if (counttot >= 3):
            print("THIS IS REAL NEWS ")
            print("The count is:", counttot)

        elif (counttot < 3):
            print("The count is:", counttot)
            print("THIS IS FAKE NEWS")
        
        


        # 6. Display the processed text and the results
        
        context = {'headline':soup.recHeadline, 'words': soup.extractText, 'url' : url,
                   'counttot': counttot,
                   
                   }

        return render(request, '/home/lewis/Documents/FakeNewsProject/fakenewsgui/myapp/templates/results.html', context)
    else:
        #user to add a url
        return render(request, '/home/lewis/Documents/FakeNewsProject/fakenewsgui/myapp/templates/urlForm.html')

fakenewsgui/myapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    
    <div class="card w-10">
        <div class="card-body">
            
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
       
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="#">Documentation</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Contacts
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="mailto:lewisker033@gmail.com">Email</a>
                <a class="dropdown-item" href="twitter.com/">Twitter</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="https://github.com/SiwelKe/fakenewsproject">Github</a>
              </div>
            </li>
           
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>


      <div class="p-3 mb-2 bg-dark text-white".bg-gradient-secondary>


<div class="container-fluid">
     
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</div>
</div>

</div>
</div>

</body>
</html>

fakenewsgui/myapp/templates/results-copy.html
{% extends 'base.html' %}
{% block extrahead %}
	<title>Detection of fake news</title>
	<meta property="og:title" content="Detection of fake news">
	<meta property="twitter:title" content="Detection of fake news">
	<meta property="og:image" content="https://www.unslanted.net/static/crowdnews/robobrain_md.png">
	<meta property="twitter:image" content="https://www.unslanted.net/static/crowdnews/robobrain_md.png">


	<meta property="og:description" content="New artificial intelligence can detect fake news with high accuracy. Give it a try!">
	<meta property="twitter:description" content="New artificial intelligence can detect fake news with high accuracy. Give it a try!">
	<meta name="description" content="Detection of fake news">
	<meta name="keywords" content="artificial intelligence natural language processing news fake news detection">
	<meta property="og:url" content="https://www.unslanted.net/fakenewsdetector/">
	<meta property="twitter:url" content="https://www.unslanted.net/fakenewsdetector/">
	<meta property="og:type" content="article">
	<meta property="twitter:type" content="article">
<link rel="canonical" href="https://www.unslanted.net/fakenewsdetector/" />
<meta name="twitter:partner" content="unslanted.net">
<meta name="twitter:card" content="summary">
<style>
input[type=url] {
  border: 2px solid blue;
  border-radius: 4px;
}
input[type=submit] {
  border: 2px solid blue;
  border-radius: 4px;
}

</style>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.2.0/css/bootstrap-slider.min.css" />
{% endblock %}

{% block content %}
<div class="row row row-fluid">
	<div class="wpb_column columns small-12 medium-12">
		<div class="vc_column-inner  ">
			<div class="wpb_wrapper">

	<h2>Analysis of <a href="{{ url }}">{{ headline }}</a><br><br></h2>

	<!--<a href="base.html"><button class="btn btn-primary btn btn-primary">Analyze another</button></a>-->


	<h3 style="text-align: center;">
	Combined Result:<br>
	{% if fin_totFake >= fin_totReal %}
		Fake/Dodgy
	{% else %}
		Seems Legit/True
	{% endif %}
	</h3>
	
	
	<br>

Probability of Fake: {{ fin_probabilities.0|floatformat }}% chance of Fake
<div class="progress">
  <div class="progress-bar" id="fakeProb_bar" role="progressbar" aria-valuenow="{{ fin_probabilities.0 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ fin_probabilities.0 }}%"></div>
</div>
	 
	<br>

Probability of Dodgy: {{ fin_probabilities.1|floatformat }}% chance of Dodgy
<div class="progress">
  <div class="progress-bar" id="MfakeProb_bar" role="progressbar" aria-valuenow="{{ fin_probabilities.1 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ fin_probabilities.1 }}%"></div>
</div>
	 
	<br>

Probability of Mostly True: {{ fin_probabilities.2|floatformat }}% chance of Mostly True
<div class="progress">
  <div class="progress-bar" id="MtrueProb_bar" role="progressbar" aria-valuenow="{{ fin_probabilities.2 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ fin_probabilities.2 }}%"></div>
</div>
	 
	<br>

Probability of True: {{ fin_probabilities.3|floatformat }}% chance of True
<div class="progress">
  <div class="progress-bar" id="trueProb_bar" role="progressbar" aria-valuenow="{{ fin_probabilities.3 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ fin_probabilities.3 }}%"></div>
</div>


<br><br><hr><br><br>
	<h2 style="text-align: center;">
	Individual model results
	</h2>


	<h3 style="text-align: center;">
	Support Vector Classifier Result:<br>
	{% if svc_totFake >= svc_totReal %}
		Fake/Dodgy
	{% else %}
		Seems Legit/True
	{% endif %}
	</h3>
	
	<br>

Probability of Fake: {{ svc_probabilities.0|floatformat }}% chance of Fake
<div class="progress">
  <div class="progress-bar" id="fakeProb_bar" role="progressbar" aria-valuenow="{{ svc_probabilities.0 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ svc_probabilities.0 }}%"></div>
</div>
	 
	<br>

Probability of Dodgy: {{ svc_probabilities.1|floatformat }}% chance of Dodgy
<div class="progress">
  <div class="progress-bar" id="MfakeProb_bar" role="progressbar" aria-valuenow="{{ svc_probabilities.1 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ svc_probabilities.1 }}%"></div>
</div>
	 
	<br>

Probability of Mostly True: {{ svc_probabilities.2|floatformat }}% chance of Mostly True
<div class="progress">
  <div class="progress-bar" id="MtrueProb_bar" role="progressbar" aria-valuenow="{{ svc_probabilities.2 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ svc_probabilities.2 }}%"></div>
</div>
	 
	<br>

Probability of True: {{ svc_probabilities.3|floatformat }}% chance of True
<div class="progress">
  <div class="progress-bar" id="trueProb_bar" role="progressbar" aria-valuenow="{{ svc_probabilities.3 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ svc_probabilities.3 }}%"></div>
</div>
	 
	<br><hr><br>

	<br><hr><br>
	
	
	<h3 style="text-align: center;">
	Gaussian Naive Bayes Result:<br>
	{% if gnb_totFake >= gnb_totReal %}
		Fake/Dodgy
	{% else %}
		Seems Legit/True
	{% endif %}
	</h3>
	
	<br>

Probability of Fake: {{ gnb_probabilities.0|floatformat }}% chance of Fake
<div class="progress">
  <div class="progress-bar" id="fakeProb_bar" role="progressbar" aria-valuenow="{{ gnb_probabilities.0 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ gnb_probabilities.0 }}%"></div>
</div>
	 
	<br>

Probability of Dodgy: {{ gnb_probabilities.1|floatformat }}% chance of Dodgy
<div class="progress">
  <div class="progress-bar" id="GfakeProb_bar" role="progressbar" aria-valuenow="{{ gnb_probabilities.1 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ gnb_probabilities.1 }}%"></div>
</div>
	 
	<br>

Probability of Mostly True: {{ gnb_probabilities.2|floatformat }}% chance of Mostly True
<div class="progress">
  <div class="progress-bar" id="GtrueProb_bar" role="progressbar" aria-valuenow="{{ gnb_probabilities.2 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ mlp_probabilities.2 }}%"></div>
</div>

Probability of True: {{ gnb_probabilities.3|floatformat }}% chance of True
<div class="progress">
  <div class="progress-bar" id="trueProb_bar" role="progressbar" aria-valuenow="{{ gnb_probabilities.3 }}"
  aria-valuemin="0" aria-valuemax="100" style="width:{{ gnb_probabilities.3 }}%"></div>
</div>























	<hr>
	<b>What is this thing?</b><br>
This artificial intelligence can predict whether a news article is fake or real based on the words used in the article.

<br><br>

<b>How to use?</b><br>
Enter a URL in the box above, the bot will load the article, extract the visible text, and 
use 4 different AI models to make a prediction of
whether the article is fake or real.
This may take several seconds because the URL you enter has to be loaded and processed.
You will get a probability distribution and a final ruling. <br><br>

<b>Any article I want?</b><br> 
The model has been trained only on a dataset that tried to cover vast topics and thus it's likely to
produce credible results for any domain 
<br><br>

<b>If you have more questions, comments, and concerns</b>
<a href="mailto:lewisker033@gmail.com">Email me here</a>

<br><br>

<br><br><br>
			</div>
		</div>
	</div>
</div>
<br><br><br>
			</div>
		</div>
	</div>
</div>
{% endblock %}			

fakenewsgui/myapp/templates/urlForm-copy.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block extrahead %}
	<title>Detection of fake news</title>
	<meta property="og:title" content="Detection of fake news">
	<meta property="twitter:title" content="Detection of fake news">
	<meta property="og:image" content="https://www.unslanted.net/static/crowdnews/robobrain_md.png">
	<meta property="twitter:image" content="https://www.unslanted.net/static/crowdnews/robobrain_md.png">

	<meta property="og:description" content="New artificial intelligence can detect fake news with high accuracy. Give it a try!">
	<meta property="twitter:description" content="New artificial intelligence can detect fake news with high accuracy. Give it a try!">
	<meta name="description" content="Detection of fake news">
	<meta name="keywords" content="artificial intelligence natural language processing news fake news detection">
	<meta property="og:url" content="https://www.unslanted.net/newsbot/">
	<meta property="twitter:url" content="https://www.unslanted.net/newsbot/">
	<meta property="og:type" content="article">
	<meta property="twitter:type" content="article">
<link rel="canonical" href="https://www.unslanted.net/newsbot/" />
<meta name="twitter:partner" content="unslanted.net">
<meta name="twitter:card" content="summary">


<style>
input[type=url] {
  border: 2px solid green;
  border-radius: 4px;
}
input[type=submit] {
  border: 2px solid green;
  border-radius: 4px;
}

</style>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.2.0/css/bootstrap-slider.min.css" />
{% endblock %}


{% block content %}
<div class="row row row-fluid">
	<div class="wpb_column columns small-12 medium-12">
		<div class="vc_column-inner  ">
			<div class="wpb_wrapper">
				<br/>

<h2 style="text-align: center;"> DETECTING FAKE NEWS USING NAIVE BAYES CLASSIFIER</h2>

<br/>

<form  method="get" >
<div class="col text-center">	
 <div class="buttonHolder">
	  <div id="div_id_entryURL" class="form-group">
		   <label for="id_entryURL" class="col-form-label  requiredField">
				Enter a URL from a news article<span class="asteriskField">*</span> </label> 

				<div class="col text-cente"></div>
				<input type="url" name="u" class="urlinput form-control" maxlength="200" id="id_entryURL" required> </div> </div> 
				<input type="submit"
					name="submit"
					value="Analyze"
    
        class="btn btn-primary btn btn-primary"
        id="submit-id-submit"
    
    
	/>
</div>
<br><br>
</div> </form>
<h3 style="text-align: center;">Results will loaded here</h3>

<b>What is this thing?</b><br>
This artificial intelligence can predict whether a news article is fake or real based on the words used in the article.

<br><br>

<b>How to use?</b><br>
Enter a URL in the box above, the bot will load the article, extract the visible text, and 
use 4 different AI models to make a prediction of
whether the article is fake or real.
This may take several seconds because the URL you enter has to be loaded and processed.
You will get a probability distribution and a final ruling. <br><br>

<b>Any article I want?</b><br> 
The model has been trained only on a dataset that tried to cover vast topics and thus it's likely to
produce credible results for any domain 
<br><br>

<b>If you have more questions, comments, and concerns</b>
<a href="mailto:lewisker033@gmail.com">Email me here</a>

<br><br>

<br><br><br>
			</div>
		</div>
	</div>
</div>


{% endblock %}

fakenewsgui/myapp/templates/urlForm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block extrahead %}
	

<style>
input[type=url] {
  border: 2px solid green;
  border-radius: 4px;
}
input[type=submit] {
  border: 2px solid green;
  border-radius: 4px;
}

</style>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.2.0/css/bootstrap-slider.min.css" />
{% endblock %}


{% block content %}
<div class="row row row-fluid">
	<div class="wpb_column columns small-12 medium-12">
		<div class="vc_column-inner  ">
			<div class="wpb_wrapper">
				<br/>

<h2 style="text-align: center;"> DETECTING FAKE NEWS USING NAIVE BAYES CLASSIFIERS</h2>

<br/>

<form  method="get" >
<div class="col text-center">	
 <div class="buttonHolder">
	  <div id="div_id_entryURL" class="form-group">
		   <label for="id_entryURL" class="col-form-label  requiredField">
				Enter a LINK from a news article<span class="asteriskField"></span> </label> 

				<div class="col text-cente"></div>
				<input type="url" name="u" class="urlinput form-control" maxlength="200" id="id_entryURL" required> </div> </div> 
				<input type="submit"
					name="submit"
					value="Analyze"
    
        class="btn btn-primary btn btn-primary"
        id="submit-id-submit"
    
    
	/>
</div>
<br><br>
</div> </form>


<b>ABOUT THIS PROJECT</b><br>
This artificial intelligence can predict whether a news article is fake or real based on the words used in the article.
Some of the algorithms used are the Naive Bayes Family such as :<br><br>
1.Bernoulli Naive Bayes<br>
2.Multinomial Naive Bayes<br>
3.Gaussian Naive Bayes classifier<br>

<br><br>

<b>HOW TO USE ?</b><br>
Enter a URL in the box above, the bot will load the article, extract the visible text, and 
use  different Naive Bayes classifier models to make a prediction of
whether the article is fake or real.
This may take several seconds because the URL you enter has to be loaded and processed.
<br><br>

<b>TYPES OF ARTICLES?</b><br> 
The model has been trained only on a dataset that tried to cover vast topics and thus it's likely to
produce credible results for any domain.Any news article is acceptable. 
<br><br>

<b>If you have any more questions or comments</b>
<a href="mailto:lewisker033@gmail.com">Email me here</a>

<br><br>

<br><br><br>
			</div>
		</div>
	</div>
</div>


{% endblock %}